sudo: false
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - '2.1'
  - '2.2'
  - jruby-19mode
env:
  - RAILS_VERSION='~> 3.2.0'
  - RAILS_VERSION='~> 4.0.0'
  - RAILS_VERSION='~> 4.1.0'
  - RAILS_VERSION='~> 4.2.0'
script:
  if [ -n "$RUBOCOP" ]; then
    bundle exec rubocop
  ; else
    bundle exec rspec
  ; fi
matrix:
  fast_finish: true
  include:
    - env: RUBOCOP=true
      rvm: default
